version: "3.9"

services:
  postgres:
    image: postgres:16
    volumes:
      - ./dev/var/postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    env_file: .env

  minio:
    image: minio/minio
    command:
      - server
      - /data
      - --address
      - :9000
      - --console-address
      - :9001
    volumes:
      - ./.local/.minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
