"""Add resume and file tables

Revision ID: f4655884046d
Revises:
Create Date: 2024-10-05 12:16:18.995496

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4655884046d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uploaded_file",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("bucket", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploaded_file")),
    )
    op.create_table(
        "resume",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pretender_name", sa.String(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "rating BETWEEN 0.0 AND 5.0",
            name=op.f("ck_resume_rating_between_0_5_range"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["uploaded_file.id"],
            name=op.f("fk_resume_file_id_uploaded_file"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resume")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resume")
    op.drop_table("uploaded_file")
    # ### end Alembic commands ###
